name: tests

on:
  pull_request:
    branches: [ lnx5 ]
    workflow_call: {}

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Restore cached sources
      id: cache-source-restore
      uses: actions/cache/restore@v3
      with:
        path: test/sources
        key: cached-sources-${{ hashFiles('test/Makefile') }}

    - name: Setup ssh keys
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ secrets.LIBUBOX_KEY }}
          ${{ secrets.UBUS_KEY }}
          ${{ secrets.UCI_KEY }}

    - name: Fetch sources
      run:  make -C test fetch

    - name: Cache sources
      if: steps.cache-source-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: test/sources
        key: ${{ steps.cache-source-restore.outputs.cache-primary-key }}



    - name: Restore cached container
      id: cache-container-restore
      uses: actions/cache/restore@v3
      with:
        path: /tmp/cached-container
        key: cached-container-${{ hashFiles('test/Dockerfile') }}

    - name: Build container
      if: steps.cache-container-restore.outputs.cache-hit != 'true'
      run: make -C test container-build

    - name: Export container
      if: steps.cache-container-restore.outputs.cache-hit != 'true'
      run: podman save netifd/test -o /tmp/cached-container

    - name: Import container
      if: steps.cache-container-restore.outputs.cache-hit == 'true'
      run: podman load < /tmp/cached-container

    - name: Cache container
      if: steps.cache-container-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: /tmp/cached-container
        key: ${{ steps.cache-container-restore.outputs.cache-primary-key }}

    - name: Run tests
      id: test
      run: make -C test container-run-tests

    - name: Archive failed
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: |
          test/results
          test/results.xml

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Testresults
        path: test/results.xml
        reporter: java-junit
